language: php

php:
  - 7.1

install:
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpcbf --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
